# Installation de nouvelles bibliothèques nécessaires

In [ ]:
!pip install tqdm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Importation et labélisation des données

In [ ]:
import os
from tqdm import tqdm
import glob
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

DATA_DIR_A = '/content/drive/MyDrive/A/'
DATA_DIR_B = '/content/drive/MyDrive/B/'
DATA_DIR_C = '/content/drive/MyDrive/C/'
DATA_DIR_D = '/content/drive/MyDrive/D/'
DATA_DIR_E = '/content/drive/MyDrive/E/'
  
LABEL_C1 = 0
#LABEL_C2 = 1
#LABEL_C3 = 2
#LABEL_C4 = 3
LABEL_C5 = 4
def load_data():
    data = []
    nbFiles = 0
    for fname in tqdm(os.listdir(DATA_DIR_A)):
        img = np.loadtxt(DATA_DIR_A + fname)
        data.append(img)
        nbFiles+=1
    
    #for fname in tqdm(os.listdir(DATA_DIR_B)):
    #    img = np.loadtxt(DATA_DIR_B + fname)
   #     data.append([img, np.array(LABEL_C2)])
  #      nbFiles+=1    
    
    #for fname in tqdm(os.listdir(DATA_DIR_C)):
   #     img = np.loadtxt(DATA_DIR_C + fname)
  #    data.append([np.array(img), np.array(LABEL_C3)])
   #     nbFiles+=1

    #for fname in tqdm(os.listdir(DATA_DIR_D)):
    #    img = np.loadtxt(DATA_DIR_D + fname)
    #    data.append([np.array(img), np.array(LABEL_C4)])
    #    nbFiles+=1

    for fname in tqdm(os.listdir(DATA_DIR_E)):
        img = np.loadtxt(DATA_DIR_E + fname)
        data.append(img)
        nbFiles+=1
        
    return data


data = load_data()
print("\n",len(data), "Files of data loaded")

100%|██████████| 100/100 [00:01<00:00, 63.71it/s]


 200 Files of data loaded


In [ ]:
data

[array([ 12.,  22.,  35., ..., -11.,   8.,  77.]),
 array([ -56.,  -50.,  -64., ..., -173., -162.,  -82.]),
 array([-37., -22., -17., ...,   3.,   4.,  82.]),
 array([-31., -43., -39., ...,  -6.,  10.,  33.]),
 array([ 14.,  26.,  32., ..., -32.,  -6., -17.]),
 array([-87., -89., -73., ...,  18.,   7.,   7.]),
 array([ -2.,  20.,  42., ..., -18.,  -6., -37.]),
 array([-31., -16.,  10., ...,   1.,   1.,   0.]),
 array([  8.,  17.,  29., ..., -40., -36.,   7.]),
 array([-41., -38., -31., ...,   1., -13.,  -1.]),
 array([ 14.,  25.,  31., ..., -26., -28.,  21.]),
 array([-64., -72., -52., ..., -36., -58.,  20.]),
 array([ 10.,  -6., -14., ...,  15.,   6., -46.]),
 array([31., 25., 17., ..., 23., 28., 65.]),
 array([ 30.,  19.,  -3., ..., -11., -13.,  -6.]),
 array([ 34.,  34.,  31., ...,  -7., -20.,  91.]),
 array([-62., -55., -44., ..., -20., -22.,  35.]),
 array([-18.,  -9.,   9., ..., 109.,  67.,  50.]),
 array([  0.,   2.,  -1., ...,  23.,  21., -16.]),
 array([-20.,  -3.,   2., ..., 

# Visualisation d'un échantillon de données

In [ ]:
"""import random
mpl.rcParams['figure.figsize'] = (20,10)

fig = plt.figure()

samples_c1 = np.empty((0, 4097), int)
while len(samples_c1) < 4:
    curID = random.randint(0, len(data))
    if data[curID][1] == LABEL_C1:
        samples_c1 = np.vstack((samples_c1, data[curID][0]))
        
samples_c2 = np.empty((0, 4097), int)
while len(samples_c2) < 4:
    curID = random.randint(0, len(data))
    if data[curID][1] == LABEL_C5:
        samples_c2 = np.vstack((samples_c2, data[curID][0]))
        
for i in range(0, 4):
    plt.subplot(421 + i * 2)
    plt.plot(samples_c1[i])
    plt.subplot(421 + i * 2 + 1)
    plt.plot(samples_c2[i])

ax = plt.subplot(421)
ax.set_title("CLASS 1")
ax = plt.subplot(422)
ax.set_title("CLASS 5")

fig.suptitle("A vs E", fontsize=20)
plt.show()"""

IndexError: ignored

<Figure size 1440x720 with 0 Axes>

In [ ]:
type(np.array(data, dtype=object))

numpy.ndarray

#Pré-traitement des données

In [ ]:
!pip install PyWavelets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pywt

In [ ]:
def wavelet_haar_pso (data):
  data=pywt.wavedec(data, 'haar',mode='sym', level=4)
  return data

In [ ]:
def wavelet_daubechie_pso (data):
  data=pywt.wavedec(data, 'db4',mode='sym', level=4)
  return data

In [ ]:
def wavelet_symlet_pso (data):
  data=pywt.wavedec(data, 'sym8',mode='sym', level=4)
  return data

In [ ]:
pywt.wavelist()

In [ ]:
wavelet_symlet_pso (data)

[array([[  196.3510768 ,   179.23483508,   181.93072161, ...,
            -6.42928256,    -8.15375885,   -36.35144646],
        [ -373.28763737,  -369.81603098,  -370.16407518, ...,
          -613.09361462,  -615.13258557,  -525.30234362],
        [  -96.07798976,   -90.493091  ,   -94.28196416, ...,
            44.35924086,    52.56063434,   -31.4147561 ],
        ...,
        [-1957.72958719, -1794.04414068, -1888.3570808 , ...,
            82.05807964,   210.74727818,   482.68430389],
        [-1035.49251003, -1030.40090674,  -982.64759166, ...,
           844.7433565 ,   727.25492568,   295.78972307],
        [  909.82418178,   680.85277433,   752.49235579, ...,
          -731.73186385,  -725.72890767,  -668.24823727]]),
 array([[ -96.51950088,  -10.90807766,   32.58586412, ...,   96.46508347,
           39.34317074,   43.95975115],
        [  56.78478591,   41.0808577 ,  -54.06887997, ...,  -44.06857376,
           54.68190893,  -17.40354573],
        [  20.69406731,  -30.15615417

In [ ]:
shuffle(data)

[[array([-458., -669., -914., ...,  356.,   87.,  215.]), array(4)],
 [array([ 134.,  390.,  446., ..., -153.,  -62.,   72.]), array(4)],
 [array([-19.,   9.,  35., ..., -53., -48.,  -1.]), array(0)],
 [array([ -9.,  15.,  35., ..., -30., -12.,  -3.]), array(0)],
 [array([ 69.,  69.,  65., ..., -17.,  -1.,  -3.]), array(0)],
 [array([-345., -166.,   91., ..., -472., -302.,  940.]), array(4)],
 [array([-187., -132.,  -53., ..., -130., -150.,  375.]), array(4)],
 [array([343., 311., 284., ..., 480., 397., 217.]), array(4)],
 [array([-51., -42., -39., ...,  -2.,   0., -49.]), array(0)],
 [array([-17., -36., -52., ...,  -6., -31., -19.]), array(0)],
 [array([-41., -37., -29., ..., -20., -23., -59.]), array(0)],
 [array([ -88., -115., -140., ...,  146.,  140.,  191.]), array(4)],
 [array([-31., -43., -39., ...,  -6.,  10.,  33.]), array(0)],
 [array([-459., -778., -981., ...,   -8.,  -11.,  949.]), array(4)],
 [array([ -114.,  -248.,  -388., ...,   484.,   397., -1566.]), array(4)],
 [array

# Préparation des données

In [ ]:
X_train

array([array([ 196.3510768 ,  179.23483508,  181.93072161,  163.83721981,
               184.25158489,  184.51687767,  189.85223306,   15.32473   ,
               108.13538151,  -18.90867574,   53.11403373,  159.43148789,
                -8.58091045,  -44.84426535,  -37.52076054,  159.28428833,
                63.40775591, -130.60286251,  184.1691861 ,   55.72093691,
                 8.07636695,  -85.65322196, -133.53342863,  -49.01608259,
                14.92596355,  100.50327779,  181.50106022,  233.79205979,
              -150.47543681,   54.86098676,   74.15157072,  110.46631038,
               -62.0675572 ,  -49.37184974,  101.16196875,  143.97457086,
                37.43132415,   78.18644454,  -34.85468135,   97.8750972 ,
                -7.57223186,   72.01039279,  -47.43180063,  -93.97510387,
              -119.97612052, -447.96989598, -220.10281788,  -70.67871186,
                53.91878649,  110.43130421, -163.70354113,  -59.16807819,
               -43.02290973,  -18.1059

In [ ]:
import numpy as np
from sklearn.utils import shuffle

data=wavelet_symlet_pso (data)
data = shuffle(data)

nb_train = round(len(data) * 0.8)
data_train = data[0:nb_train]
data_test = data[nb_train:]

X_train = np.array([d[0] for d in data_train])
Y_train = np.array([d[1] for d in data_train])

X_test = np.array([d[0] for d in data_test])
Y_test = np.array([d[1] for d in data_test])

X_train.shape
    
X_train = X_train.reshape(4097, 1)
Y_train = Y_train.reshape(Y_train.shape[0], 1)

X_test = X_test.reshape(X_test.shape[0], 4097, 1)
Y_test = Y_test.reshape(Y_test.shape[0], 1)


/usr/local/lib/python3.8/dist-packages/pywt/_multilevel.py:90: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.asarray(data)


ValueError: ignored

# Construction du modèle LSTM (RNN)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import LSTM

#num_steps = 30
batch_size = 4
nb_epoch = 100
hidden_size = 64
use_dropout=True

model = Sequential()
model.add(LSTM(hidden_size, input_shape=(4097,1)))
#model.add(LSTM(64, return_sequences=False))

if use_dropout:
  model.add(Dropout(0.35))
model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['mae', 'acc'])

print(model.summary())

history = model.fit(X_train, Y_train, validation_split=0.2, batch_size=batch_size, nb_epoch=nb_epoch)
score = model.evaluate(X_test, Y_test, batch_size=batch_size)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 64)                16896     
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 65        
                                                                 
 activation_1 (Activation)   (None, 1)                 0         
                                                                 
Total params: 16,961
Trainable params: 16,961
Non-trainable params: 0
_________________________________________________________________
None


NameError: ignored